default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: root
  host: localhost


development:
  <<: *default
  database: shoes_development

test:
  <<: *default
  database: shoes_test

production:
  <<: *default
  database: shoes_production
  username: postgres
  password: root
