default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: shoes_development

test:
  <<: *default
  database: shoes_test

production:
  <<: *default
  database: shoes_production
  username: shoes
  password: <%= ENV['MYSQL_DEMO_DATABASE_PASSWORD'] %>
