default: &default
  adapter: pg
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root


development:
  <<: *default
  database: shoes_development

test:
  <<: *default
  database: shoes_test

production:
  <<: *default
  database: shoes_production
  username: shoes
  password: <%= ENV['MYSQL_DEMO_DATABASE_PASSWORD'] %>
  adapter: mysql
